//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHUYENXE
    {
        public CHUYENXE()
        {
            this.VEXEs = new HashSet<VEXE>();
        }
    
        public string MACHUYEN { get; set; }
        public string TENCHUYEN { get; set; }
        public string MATUYEN { get; set; }
        public Nullable<System.TimeSpan> GIODI { get; set; }
        public Nullable<System.TimeSpan> GIODEN { get; set; }
        public Nullable<byte> CHOTRONG { get; set; }
        public Nullable<short> MANV { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual TUYENXE TUYENXE { get; set; }
        public virtual ICollection<VEXE> VEXEs { get; set; }
    }
}
