//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAIXE
    {
        public LOAIXE()
        {
            this.XEs = new HashSet<XE>();
        }
    
        public short MALOAIXE { get; set; }
        public string TENLOAIXE { get; set; }
    
        public virtual ICollection<XE> XEs { get; set; }
    }
}
