//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        public NHANVIEN()
        {
            this.CHUYENXEs = new HashSet<CHUYENXE>();
            this.VEXEs = new HashSet<VEXE>();
        }
    
        public short MANV { get; set; }
        public string TENDN { get; set; }
        public string MATKHAU { get; set; }
        public string TENNV { get; set; }
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        public string GIOITINH { get; set; }
        public string DIACHI { get; set; }
        public Nullable<decimal> CMND { get; set; }
        public Nullable<decimal> DIENTHOAI { get; set; }
        public string EMAIL { get; set; }
        public Nullable<short> MALOAINV { get; set; }
    
        public virtual ICollection<CHUYENXE> CHUYENXEs { get; set; }
        public virtual MALOAINV MALOAINV1 { get; set; }
        public virtual ICollection<VEXE> VEXEs { get; set; }
    }
}
