//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEXE
    {
        public short MAVE { get; set; }
        public short MAKH { get; set; }
        public Nullable<short> MANV { get; set; }
        public string MACHUYENXE { get; set; }
        public Nullable<short> MAXE { get; set; }
        public Nullable<byte> VITRIGHENGOI { get; set; }
        public string GHICHU { get; set; }
    
        public virtual CHUYENXE CHUYENXE { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual XE XE { get; set; }
    }
}
