//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XE
    {
        public XE()
        {
            this.VEXEs = new HashSet<VEXE>();
        }
    
        public short MAXE { get; set; }
        public string TENXE { get; set; }
        public string BIENSO { get; set; }
        public Nullable<byte> SOGHE { get; set; }
        public short MALOAIXE { get; set; }
    
        public virtual LOAIXE LOAIXE { get; set; }
        public virtual ICollection<VEXE> VEXEs { get; set; }
    }
}
